import org.gradle.internal.os.OperatingSystem

plugins {
	id 'java'
	id 'application'
	id "org.jetbrains.kotlin.jvm" version "2.2.0"
	id "org.jetbrains.kotlin.plugin.serialization" version "2.2.0"
}

project.ext.lwjglVersion = "3.3.6"

switch (OperatingSystem.current()) {
	case OperatingSystem.LINUX:
		project.ext.lwjglNatives = "natives-linux"
		def osArch = System.getProperty("os.arch")
		if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
			project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
		} else if  (osArch.startsWith("ppc")) {
			project.ext.lwjglNatives += "-ppc64le"
		} else if  (osArch.startsWith("riscv")) {
			project.ext.lwjglNatives += "-riscv64"
		}
		break
	case OperatingSystem.MAC_OS:
		project.ext.lwjglNatives = "natives-macos"
		break
	case OperatingSystem.WINDOWS:
		project.ext.lwjglNatives = "natives-windows"
		break
}

mainClassName = 'com.morph.engine.core.EngineLauncher'
//project.ext.lwjglVersion = "3.1.6"

tasks.register('execute', JavaExec) {
	main = mainClassName
	classpath = sourceSets.main.runtimeClasspath
}

tasks.register('sourcesJar', Jar) {
	dependsOn classes
	archiveClassifier = "sources"
	from sourceSets.main.java.srcDirs, sourceSets.main.kotlin.srcDirs
}

repositories {
	mavenCentral()
	maven { url "https://kotlin.bintray.com/kotlinx" }
	maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
	maven { url "https://jitpack.io" }
}

dependencies {
	implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

	implementation "org.lwjgl:lwjgl"
	implementation "org.lwjgl:lwjgl-assimp"
	implementation "org.lwjgl:lwjgl-glfw"
	implementation "org.lwjgl:lwjgl-openal"
	implementation "org.lwjgl:lwjgl-opengl"
	implementation "org.lwjgl:lwjgl-stb"
	runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-assimp::$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"
	api 'io.reactivex.rxjava2:rxkotlin:2.4.0'
	api 'io.reactivex.rxjava2:rxjava:2.2.21'
	api 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
	api "org.jetbrains.kotlin:kotlin-compiler"
//	compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
//	api "org.jetbrains.kotlin:kotlin-script-util"
	api "org.jetbrains.kotlin:kotlin-scripting-jsr223"

	implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1'

	testImplementation "org.jetbrains.kotlin:kotlin-test"
}
